---
# tasks file for nexus
- name: Update yum
  yum:
    update_cache: true

- name: install java
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Add nexus Group
  group:
    name: nexus
    state: present

- name: Add nexus user
  user:
    name: nexus
    state: present
    group: nexus    
  

- name: Download nexus tar file
  get_url:
    url: 'https://download.sonatype.com/nexus/3/latest-unix.tar.gz'
    dest: /opt/nexus.tar.gz
    mode: 0755
  



- name: Unzip tar file nexus
  unarchive:
    src: /opt/nexus.tar.gz
    dest: /opt
    mode: 0755
    remote_src: yes


- name: Rename folder nexus3.* -> nexus
  copy:
    src: /opt/nexus-3.58.1-02/
    dest: /opt/nexus
    owner: nexus
    group: nexus
    remote_src: yes

- name: create nexus properties
  lineinfile:
    path: /etc/sudoers
    line: |
      nexus ALL=(ALL) NOPASSWD: ALL
    state: present

- name: restart sshd
  systemd:
    name: sshd
    state: restarted   
# - name: create nexus vmoptions
#   template:
#     src: /templates/vmoptions.j2
#     dest: /opt/nexus/bin/nexus.vmoptions

- name: Run as user nexus
  template:
    src: nexus.rc.j2
    dest: /opt/nexus/bin/nexus.rc

- name: Add Vmoptions
  template:
    src: vmoptions.j2
    dest: /opt/nexus/bin/nexus.vmoptions

  

- name: Add systemD
  template:
    src:  systemDconfig.j2
    dest: /etc/systemd/system/nexus.service

- name: Open Firewall Port RedHat
  firewalld:
    zone: public
    port: 9000/tcp
    permanent: true
    state: enabled
    immediate: true
  when: ansible_os_family == 'RedHat'


- name: daemon-reload
  systemd:
    name: nexus
    daemon-reload: true
    state: restarted

- name: start nexus
  service:
    name: nexus
    state: started
  